//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaevalFightForFood.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameDescriptionResourcesEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameDescriptionResourcesEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaevalFightForFood.Resources.GameDescriptionResourcesEn", typeof(GameDescriptionResourcesEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archer.
        /// </summary>
        public static string Archer {
            get {
                return ResourceManager.GetString("Archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrey&amp;Sergey Dryominy.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannon.
        /// </summary>
        public static string Cannon {
            get {
                return ResourceManager.GetString("Cannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector.
        /// </summary>
        public static string Collector {
            get {
                return ResourceManager.GetString("Collector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First side green - 2 food collectors (the only ones who can stand on food but can&apos;t attack and die instantly upon any attack without dealing damage), 2 archers (deal 2 damage horizontally and vertically and 1 diagonally, die instantly without dealing damage when attacked) and 1 shovelman (the only unit with 2 HP, both die when attacking each other with equal HP, or lose 1 HP when attacking a knight);
        ///    Second side red - 1 collector, 2 knights (1 HP and attack on 1 cell, if attacked by a shovelman, the la [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DescriptionBody {
            get {
                return ResourceManager.GetString("DescriptionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Description.
        /// </summary>
        public static string DescriptionHeader {
            get {
                return ResourceManager.GetString("DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Units.
        /// </summary>
        public static string GreenUnits {
            get {
                return ResourceManager.GetString("GreenUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        public static string Knight {
            get {
                return ResourceManager.GetString("Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Units.
        /// </summary>
        public static string RedUnits {
            get {
                return ResourceManager.GetString("RedUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shovelman.
        /// </summary>
        public static string Shovelman {
            get {
                return ResourceManager.GetString("Shovelman", resourceCulture);
            }
        }
    }
}
