//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaevalFightForFood.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameDescriptionRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameDescriptionRu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaevalFightForFood.Resources.GameDescriptionRu", typeof(GameDescriptionRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучник.
        /// </summary>
        public static string Archer {
            get {
                return ResourceManager.GetString("Archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторы: Андрей и Сергей Дрёмины.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пушка.
        /// </summary>
        public static string Cannon {
            get {
                return ResourceManager.GetString("Cannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сборщик.
        /// </summary>
        public static string Collector {
            get {
                return ResourceManager.GetString("Collector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первая сторона зелёные - 2 сборщика еды (единственные , кто могут стоять на еде, но не умеют атаковать и гибнут сразу при любой атаке не нанося урон), 2 лучника (бьют на 2 по горизонтали и вертикали и на одну по диогонали, если их атакуют гибнут сразу не нанося урон) и 1 лопатник(единственный юнит у кого есть 2 HP и при атаке лопатника оба погибают , если у них равное HP или теряет 1 HP , атакуя рыцаря);
        ///    Вторая сторона красные - 1 сборщик, 2 рыцаря (1 HP и атакуют на 1 клетку, если атакует лопатник, то [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DescriptionBody {
            get {
                return ResourceManager.GetString("DescriptionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание игры.
        /// </summary>
        public static string DescriptionHeader {
            get {
                return ResourceManager.GetString("DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зелёные юниты.
        /// </summary>
        public static string GreenUnits {
            get {
                return ResourceManager.GetString("GreenUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рыцарь.
        /// </summary>
        public static string Knight {
            get {
                return ResourceManager.GetString("Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Красные юниты.
        /// </summary>
        public static string RedUnits {
            get {
                return ResourceManager.GetString("RedUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лопатник.
        /// </summary>
        public static string Shovelman {
            get {
                return ResourceManager.GetString("Shovelman", resourceCulture);
            }
        }
    }
}
